aws_region = "us-east-1"
vpc_cidr = "172.18.0.0/16"
net_public_count = "2"
net_private_count = "2"
efs_mt_count = "2"
postgres_instance = "db.t2.micro"
elasticache_type = "cache.t2.micro"
elasticache_parameter_group = "default.redis3.2"
